---
  - name: Install and configure tomcat
    hosts: webservers
    gather_facts: false
    tasks:
      - name: Updating repos
        become: yes
        yum:
          name: "*"
          state: latest
      - name: Installing required java
        become: yes
        yum:
          name: java-1.8.0-openjdk
          state: present
      - name:
        become: yes
        alternatives:
          name: java
          link: /usr/bin/java
          path: /usr/lib/jvm/jre-1.8.0-openjdk/bin/java
      - name: Downloading required java
        become: yes
        get_url:
          url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.50/bin/apache-tomcat-9.0.50.tar.gz
          dest: /usr/local
      - name: Extracting downloaded Tomcat
        become: yes
        unarchive:
          src: "/usr/local/apache-tomcat-9.0.50.tar.gz"
          dest: /usr/bin
          remote_src: yes
      - name: Renaming tomcat home
        become: yes
        command: mv /usr/bin/apache-tomcat-9.0.50 /usr/bin/latest
      - name: Change file ownership, group and permissions
        become: yes
        ansible.builtin.file:
          path: /usr/bin/latest/bin
          owner: azureuser
          mode: '1777'
      - name: Starting tomcat
        become: yes
        shell: nohup usr/bin/latest/bin/startup.sh &
